import type {Metadata} from "next";
import "./globals.css";
import Lightfall from "@/app/components/Lightfall";
import ResetAllButton from "@/app/components/ResetAllButton";
import CoffeeFall from "@/app/components/CoffeeFall";


export const metadata: Metadata = {
    title: "TORABIKA",
    description: "Generated by Realashrafi",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={` h-full antialiased`}
        >
        <body className="min-h-full flex flex-col">

        <div style={{width: '100%', height: '100vh', position: 'fixed'}}>
            <CoffeeFall images={['head.png', 'Logo.png', 'flip7.png','PS5.png',
                'A56.png',
                'A16.png',
                'flip7.png',
                'CHARGE6.png',
                'WaveBeam.png',
                'tune720.png',
                'BLACKSHARCK.png',
                'oneyear.png',]} />
        </div>

        <ResetAllButton/>
        {children}</body>
        </html>
    );
}
