import type {Metadata} from "next";
import "./globals.css";
import Lightfall from "@/app/components/Lightfall";
import ResetAllButton from "@/app/components/ResetAllButton";


export const metadata: Metadata = {
    title: "TORABIKA",
    description: "Generated by Realashrafi",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={` h-full antialiased`}
        >
        <body className="min-h-full flex flex-col">

        <div style={{width: '100%', height: '100vh', position: 'fixed'}}>
            <Lightfall
                colors={['#D50011', '#ffffff', '#ffffff']}
                backgroundColor="#ffffff"
                speed={0.3}
                streakCount={1}
                streakWidth={1}
                streakLength={1}
                glow={1}
                density={0.6}
                twinkle={1}
                zoom={1}
                backgroundGlow={0.1}
                opacity={1}
                mouseInteraction
                mouseStrength={0.5}
                mouseRadius={1}
            />
        </div>

        <ResetAllButton/>
        {children}</body>
        </html>
    );
}
