import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Lightfall from "@/app/components/Lightfall";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TORABIKA",
  description: "Generated by Realashrafi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <div style={{ width: '100%', height: '100vh', position: 'fixed' }}>
        <Lightfall
            colors={['#D50011', '#D50011', '#D50011']}
            backgroundColor="#EEEEF"
            speed={0.3}
            streakCount={3}
            streakWidth={1}
            streakLength={1}
            glow={1}
            density={0.6}
            twinkle={1}
            zoom={1}
            backgroundGlow={0.1}
            opacity={1}
            mouseInteraction
            mouseStrength={0.5}
            mouseRadius={1}
        />
      </div>
      {children}</body>
    </html>
  );
}
